# Generated by Django 5.0 on 2023-12-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='p.jpg', null=True, upload_to=''),
        ),
    ]
