# Generated by Django 5.0 on 2023-12-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
