# Generated by Django 4.2.7 on 2023-11-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_options_post_created_at_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-created_at_time']},
        ),
        migrations.AddField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(default=0),
        ),
    ]
