# Generated by Django 4.2.7 on 2023-12-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_post_options_remove_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(max_length=200, unique_for_date=''),
        ),
    ]
